markdown: kramdown
permalink: /:categories/:title.html
highlighter: rouge
name: Geralt Luo
# url: https://oplancelot.github.io
url: https://cloud-architecture.online
twitter: 
sass:
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

